# Generated by Django 3.0.4 on 2020-08-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20170110_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='action',
            field=models.PositiveSmallIntegerField(default='UP'),
        ),
    ]
